version: '3.7'

services:
  pypi-server:
    image: pypiserver/pypiserver:latest
    platform: linux/amd64
    restart: always
    ports:
      - "80:8080"
    volumes:
      - ~/.htpasswd:/data/.htpasswd
    command:
      - run
      - -P
      - .htpasswd/htpasswd.txt
      - --overwrite

